name: Sync (pull) changes from Overleaf to this repository

on:
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'

jobs:
  sync-job:
    if: startsWith(vars.OVERLEAF_READ_URL, 'https://www.overleaf.com/read/')

    runs-on: ubuntu-latest

    env:
      OVERLEAF_READ_URL: ${{ vars.OVERLEAF_READ_URL }}
      SKRIPSI_DIR_NAME: 'skripsi'
      TEMP_ZIP_FILE_NAME: 'temp-skripsi-archive.zip'
      TEMP_COOKIEVAL_FILE_NAME: 'temp-cookie-value.txt'
      TEMP_DLURL_FILE_NAME: 'temp-download-url.txt'

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3

    - run: npm install puppeteer
      
    - name: Authorize
      run: |
        const puppeteer = require('puppeteer');
        const fs = require('fs').promises;
        
        (async () => {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();

          await page.goto(process.env.OVERLEAF_READ_URL);
          await page.waitForSelector('div.pdfViewer');

          const cookies = await page.cookies();
          const sessionCookieName = 'overleaf_session2';
          const sessionCookieValue = cookies.find((item) => item.name === sessionCookieName).value;

          await fs.writeFile('./' + process.env.TEMP_COOKIEVAL_FILE_NAME, `${sessionCookieName}=${sessionCookieValue}`);
          await fs.writeFile('./' + process.env.TEMP_DLURL_FILE_NAME, `${await page.url()}/download/zip`);

          await browser.close();
        })()
      shell: node

    - name: Retrieve
      run: wget -O $TEMP_ZIP_FILE_NAME --header "cookie: $(cat $TEMP_COOKIEVAL_FILE_NAME)" $(cat $TEMP_DLURL_FILE_NAME)

    - name: Hash
      run: |
        OBTAINED_HASH=$(sha256sum $TEMP_ZIP_FILE_NAME)
        echo "UNIQUE_COMMIT_IDENTITY=${OBTAINED_HASH:0:10}" >> "$GITHUB_ENV"

    - name: Apply
      run: |
        rm -rf $SKRIPSI_DIR_NAME
        unzip $TEMP_ZIP_FILE_NAME -d $SKRIPSI_DIR_NAME

    - name: Clean-up
      run: rm $TEMP_ZIP_FILE_NAME $TEMP_COOKIEVAL_FILE_NAME $TEMP_DLURL_FILE_NAME

    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --all
        git commit -m "Update ($UNIQUE_COMMIT_IDENTITY)" && git push || echo "Files in this repository are already up-to-date."
